/* Report service — generates diagnostic reports in JSON, CSV, and printable HTML.
   All generation is client-side; no data sent to any server. */

function uid8() { return Math.random().toString(36).slice(2, 10).toUpperCase(); }

export const reportService = {
  generateId() { return `AGR-${Date.now()}-${uid8()}`; },

  toJson(record) {
    return JSON.stringify(record, null, 2);
  },

  toCsv(record) {
    const rows = [
      ["Field", "Value"],
      ["Report ID",          record.reportId || ""],
      ["Date",               record.createdAt || ""],
      ["Domain",             record.domainId || ""],
      ["Species",            record.species || ""],
      ["Primary Diagnosis",  record.primaryDiagnosis || ""],
      ["Severity",           record.severity?.label || ""],
      ["Confidence",         record.confidence?.label || ""],
      ["Confidence Score",   record.confidence?.score?.toFixed(2) || ""],
      ["Urgency",            record.risk?.urgency?.label || ""],
      ["Spread Risk",        record.risk?.spread?.label || ""],
      ["Economic Impact",    record.risk?.economicImpact?.label || ""],
      ["Needs Expert",       record.needsExpertReview ? "Yes" : "No"],
      ["Follow-up (days)",   record.followUp?.days || ""],
      ["Recovery Timeline",  record.recoveryTimeline || ""],
      ["Disclaimer",         record.disclaimer || ""],
    ];

    // Add observations
    (record.observations || []).forEach((o, i) => rows.push([`Observation ${i + 1}`, o]));

    // Add immediate actions
    (record.recommendations?.immediate || []).forEach((a, i) =>
      rows.push([`Immediate Action ${i + 1}`, typeof a === "string" ? a : a.text])
    );

    return rows.map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  },

  toPrintableHtml(record) {
    const domain  = (record.domainId || "").toUpperCase();
    const date    = new Date(record.createdAt || Date.now()).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
    const obs     = (record.observations || []).map((o) => `<li>${esc(o)}</li>`).join("");
    const imm     = (record.recommendations?.immediate || []).map((a) => `<li>${esc(typeof a === "string" ? a : a.text)}</li>`).join("");
    const organic = (record.recommendations?.organic || []).map((a) => `<li>${esc(typeof a === "string" ? a : a.text)}</li>`).join("");
    const chem    = (record.recommendations?.chemical || []).map((a) => `<li>${esc(typeof a === "string" ? a : a.text)}</li>`).join("");
    const fps     = (record.followUp?.checkPoints || []).map((c) => `<li>${esc(c)}</li>`).join("");

    return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>AgriOS Diagnostic Report — ${record.reportId || ""}</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 24px; color: #1a1a1a; }
  h1 { color: #16a34a; } h2 { color: #15803d; border-bottom: 1px solid #d1fae5; padding-bottom: 4px; }
  .badge { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 13px; font-weight: 700; }
  .meta { background: #f0fdf4; padding: 12px; border-radius: 8px; margin-bottom: 16px; }
  .disclaimer { font-size: 11px; color: #666; border-top: 1px solid #eee; margin-top: 24px; padding-top: 12px; }
  ul { margin: 6px 0; padding-left: 20px; } li { margin: 4px 0; }
  @media print { body { padding: 0; } }
</style></head><body>
<h1>🌿 AgriOS India — Diagnostic Report</h1>
<div class="meta">
  <b>Report ID:</b> ${esc(record.reportId || "N/A")} &nbsp;|&nbsp;
  <b>Domain:</b> ${esc(domain)} &nbsp;|&nbsp;
  <b>Date:</b> ${esc(date)}
  ${record.species ? `<br><b>Species/Crop:</b> ${esc(record.species)}` : ""}
</div>

<h2>Primary Diagnosis</h2>
<p><b>${esc(record.primaryDiagnosis || "Unable to Detect")}</b>
  &nbsp;<span class="badge" style="background:#dcfce7;color:#15803d">Confidence: ${esc(record.confidence?.label || "low")}</span>
  &nbsp;<span class="badge" style="background:#fee2e2;color:#991b1b">Severity: ${esc(record.severity?.label || "Unknown")}</span>
</p>

${obs ? `<h2>Observations</h2><ul>${obs}</ul>` : ""}
${imm ? `<h2>Immediate Actions</h2><ul>${imm}</ul>` : ""}
${organic ? `<h2>Organic Treatment</h2><ul>${organic}</ul>` : ""}
${chem ? `<h2>Chemical Treatment</h2><ul>${chem}</ul>` : ""}
${fps ? `<h2>Follow-up Checkpoints (${record.followUp?.days || 7} days)</h2><ul>${fps}</ul>` : ""}
${record.recoveryTimeline ? `<h2>Recovery Timeline</h2><p>${esc(record.recoveryTimeline)}</p>` : ""}

<div class="disclaimer">
  <b>⚠️ DISCLAIMER:</b> ${esc(record.disclaimer || "AI-based prediction only. Not a confirmed diagnosis.")}
  <br>This report was generated by AgriOS India AI Diagnostic System.
</div></body></html>`;
  },

  downloadJson(record) {
    const id   = record.reportId || this.generateId();
    download(`agrios-report-${id}.json`, this.toJson(record), "application/json");
  },

  downloadCsv(record) {
    const id = record.reportId || this.generateId();
    download(`agrios-report-${id}.csv`, this.toCsv(record), "text/csv");
  },

  print(record) {
    const html = this.toPrintableHtml(record);
    const win  = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
  },
};

function esc(str) { return String(str || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }

function download(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
