/* Curated central + major state government schemes for Indian farmers.
   Rules are simplified for eligibility screening; always confirm at the official
   portal before applying — rules change with each budget/notification.
   Source: respective ministry websites (as of 2024-25). */

/* Eligibility rule fields:
   landMin / landMax   — acres (null = no limit)
   farmTypes           — array of farm types that qualify (null = all)
   categories          — farmer category: small | marginal | large | all
   states              — specific states (null = all India)
   incomeMax           — annual income ceiling in ₹ (null = no limit)
   needsBankAccount    — bool
   needsAadhar         — bool
   needsLandRecord     — bool
*/

export const SCHEMES = [
  {
    id: "pm-kisan",
    title: "PM-KISAN",
    fullName: "Pradhan Mantri Kisan Samman Nidhi",
    category: "income",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    offer: "₹6,000/year in 3 equal instalments of ₹2,000 directly in your bank account.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: null,
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: true,
    },
    excludes: "Institutional landholders, constitutional post holders, current/retired govt employees (income tax payers), and professionals (doctors, engineers, lawyers, CAs).",
    documents: ["Aadhaar card", "Land ownership records (Khata/Khasra)", "Bank passbook"],
    applyUrl: "https://pmkisan.gov.in",
    applyHow: "Register at pmkisan.gov.in or through your local patwari / agriculture department.",
    accent: "primary",
    icon: "Landmark",
  },
  {
    id: "pmfby",
    title: "PMFBY",
    fullName: "Pradhan Mantri Fasal Bima Yojana",
    category: "insurance",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    offer: "Crop insurance covering losses from natural calamities, pests and diseases. Premium: 2% for kharif, 1.5% for rabi, 5% for horticulture/commercial crops.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: ["crop", "horti"],
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: true,
    },
    excludes: "Livestock, fisheries. Coverage limited to notified crops in notified areas.",
    documents: ["Aadhaar card", "Land records / crop sown declaration", "Bank passbook"],
    applyUrl: "https://pmfby.gov.in",
    applyHow: "Apply through your bank (if you have a KCC loan it may be automatic), CSC centre, or the PMFBY app before the cut-off date for each season.",
    accent: "blue",
    icon: "ShieldCheck",
  },
  {
    id: "kcc",
    title: "Kisan Credit Card",
    fullName: "Kisan Credit Card Scheme",
    category: "credit",
    ministry: "Ministry of Agriculture & Farmers Welfare / RBI",
    offer: "Short-term credit up to ₹3 lakh at 4% effective interest rate (after interest subvention) for crop production, post-harvest and allied activities.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: null,
      states: null,
      incomeMax: null,
      needsBankAccount: false,
      needsAadhar: true,
      needsLandRecord: true,
    },
    excludes: "Defaulters with existing overdue loans may face rejection.",
    documents: ["Aadhaar / identity proof", "Land records", "Passport photo"],
    applyUrl: "https://www.nabard.org/content1.aspx?id=567",
    applyHow: "Apply at any bank branch (NABARD, SBI, cooperative banks). PM-KISAN beneficiaries can apply via PM-KISAN portal with a single click.",
    accent: "blue",
    icon: "CreditCard",
  },
  {
    id: "pmegp",
    title: "PMEGP",
    fullName: "Prime Minister's Employment Generation Programme",
    category: "subsidy",
    ministry: "Ministry of MSME",
    offer: "Subsidy of 15–35% on project cost for setting up agro-processing or allied units. Bank loan for balance.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: ["crop", "dairy", "poultry", "goat", "fish", "horti"],
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: false,
    },
    excludes: "Age below 18. Existing beneficiaries of similar schemes for the same activity.",
    documents: ["Aadhaar", "Project report (DPR)", "Educational certificate (8th pass minimum for projects > ₹10L)", "Caste certificate if applicable"],
    applyUrl: "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
    applyHow: "Apply online at KVIC portal. Submit to District KVIC/KVIB/DIC office.",
    accent: "orange",
    icon: "Briefcase",
  },
  {
    id: "nlm",
    title: "NLM (Livestock)",
    fullName: "National Livestock Mission",
    category: "subsidy",
    ministry: "Department of Animal Husbandry & Dairying",
    offer: "Subsidy for entrepreneurship in poultry, goat, sheep, pig rearing, and feed/fodder. Up to 50% subsidy on eligible project cost.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: ["poultry", "goat", "dairy"],
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: false,
    },
    excludes: "Commercial-scale industrial units already receiving other subsidies.",
    documents: ["Aadhaar", "Bank passbook", "Land lease or ownership document", "Project proposal"],
    applyUrl: "https://nlm.udyamimitra.in",
    applyHow: "Apply through State Animal Husbandry Department or online at NLM portal.",
    accent: "orange",
    icon: "Rabbit",
  },
  {
    id: "pmmsy",
    title: "PMMSY (Fisheries)",
    fullName: "Pradhan Mantri Matsya Sampada Yojana",
    category: "subsidy",
    ministry: "Department of Fisheries",
    offer: "60% subsidy for SC/ST/women, 40% for others, on approved fish farming projects including pond construction, equipment, and boats.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: ["fish"],
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: false,
    },
    excludes: "Marine fishing vessels in notified restricted zones.",
    documents: ["Aadhaar", "Bank passbook", "Land/pond ownership/lease document", "Caste certificate if applicable"],
    applyUrl: "https://pmmsy.dof.gov.in",
    applyHow: "Apply through State Fisheries Department or online PMMSY portal.",
    accent: "blue",
    icon: "Fish",
  },
  {
    id: "soil-health",
    title: "Soil Health Card",
    fullName: "Soil Health Card Scheme",
    category: "advisory",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    offer: "Free soil testing every 2 years and a card with crop-wise fertiliser recommendations to reduce input cost and improve yield.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: ["crop", "horti"],
      states: null,
      incomeMax: null,
      needsBankAccount: false,
      needsAadhar: false,
      needsLandRecord: false,
    },
    excludes: "None.",
    documents: ["No documents required — just request at your local agriculture office or KVK."],
    applyUrl: "https://soilhealth.dac.gov.in",
    applyHow: "Contact your village-level worker (VLW), agriculture extension officer, or KVK.",
    accent: "primary",
    icon: "FlaskConical",
  },
  {
    id: "pmksy",
    title: "PM Krishi Sinchayee Yojana",
    fullName: "Pradhan Mantri Krishi Sinchayee Yojana",
    category: "subsidy",
    ministry: "Ministry of Jal Shakti",
    offer: "Subsidy on drip and sprinkler irrigation equipment (Har Khet Ko Pani + Per Drop More Crop). Up to 55% for small/marginal farmers.",
    eligibility: {
      landMax: null, landMin: 0.5,
      categories: ["small", "marginal"],
      farmTypes: ["crop", "horti"],
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: true,
    },
    excludes: "Unirrigable rocky terrain or areas already covered by canal irrigation.",
    documents: ["Aadhaar", "Land records", "Bank passbook", "Quotation for equipment"],
    applyUrl: "https://pmksy.gov.in",
    applyHow: "Apply through State Agriculture / Irrigation Department. Some states have dedicated online portals.",
    accent: "blue",
    icon: "Droplets",
  },
  {
    id: "agri-infra",
    title: "Agriculture Infrastructure Fund",
    fullName: "Agriculture Infrastructure Fund (AIF)",
    category: "credit",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    offer: "Interest subvention of 3% per annum on loans up to ₹2 crore for post-harvest management infrastructure (cold storage, silos, primary processing units).",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: null,
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: false,
    },
    excludes: "Projects not related to post-harvest value chain.",
    documents: ["Business plan/DPR", "Aadhaar", "Bank details", "Land/lease documents for project site"],
    applyUrl: "https://agriinfra.dac.gov.in",
    applyHow: "Apply online at the AIF portal; a Primary Agricultural Credit Society or FPO can also apply on behalf of members.",
    accent: "yellow",
    icon: "Building2",
  },
  {
    id: "pm-kusum",
    title: "PM-KUSUM",
    fullName: "Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan",
    category: "subsidy",
    ministry: "Ministry of New and Renewable Energy",
    offer: "Subsidy for solar pumps (up to 90% for small/marginal farmers) and grid-connected solar plants on farm/barren land to earn extra income.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal", "large"],
      farmTypes: ["crop", "horti", "dairy"],
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: true,
    },
    excludes: "Urban areas; grid-connected component requires DISCOM agreement.",
    documents: ["Aadhaar", "Land records", "Bank passbook"],
    applyUrl: "https://pmkusum.mnre.gov.in",
    applyHow: "Apply through State Nodal Agency (state energy development agency or agriculture department).",
    accent: "yellow",
    icon: "Sun",
  },
  {
    id: "fpo-scheme",
    title: "FPO Promotion Scheme",
    fullName: "Formation & Promotion of Farmer Producer Organisations",
    category: "subsidy",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    offer: "₹18 lakh over 3 years for each new FPO for handholding, management cost, and equity grant up to ₹15 lakh for matching member share capital.",
    eligibility: {
      landMax: null, landMin: null,
      categories: ["small", "marginal"],
      farmTypes: null,
      states: null,
      incomeMax: null,
      needsBankAccount: true,
      needsAadhar: true,
      needsLandRecord: false,
    },
    excludes: "Existing companies / societies not qualifying as FPO under Companies Act.",
    documents: ["FPO registration documents", "Member list", "Bank account of FPO"],
    applyUrl: "https://sfacindia.com",
    applyHow: "Contact SFAC, NABARD, or an implementing agency (NCDC). A cluster of at least 300 farmers typically forms an FPO.",
    accent: "primary",
    icon: "Users",
  },
];

export function getScheme(id) { return SCHEMES.find((s) => s.id === id) || null; }

export function searchSchemes(query) {
  const q = (query || "").toLowerCase().trim();
  if (!q) return SCHEMES;
  return SCHEMES.filter((s) =>
    s.title.toLowerCase().includes(q) ||
    s.fullName.toLowerCase().includes(q) ||
    s.category.includes(q) ||
    s.offer.toLowerCase().includes(q),
  );
}
